Library.WebApplication/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Library.Entities;
using Library.Repositories.Interfaces;
using Library.WebApplication.Services;

namespace Library.WebApplication.Controllers
{
    public class AuthorsController : Controller
    {
        private IRepository<Author> authorRepository;
        private AuthorImageService authorImageService;

        public AuthorsController(IRepository<Author> repository)
        {
            authorRepository = repository;
            authorImageService = new AuthorImageService();
        }
        // GET: Authors
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(authorRepository.GetAll());
        }

        // Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Author author)
        {
            if (ModelState.IsValid)
            {
                if (author.ImageFile != null && author.ImageFile.ContentLength > 0)
                {
                    string uploadPath = Server.MapPath("~/Files/Images/");
                    authorImageService.UpdateAuthorImageData(ref author, uploadPath);
                }

                authorRepository.Create(author);
                authorRepository.Save();

                return RedirectToAction("Index");
            }

            return View(author);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            Author author = authorRepository.GetById(id);

            if (author != null)
            {
                return View(author);
            }

            return HttpNotFound($"Author with id = {id} does not exist.");
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(Author author)
        {
            if (ModelState.IsValid)
            {
                if (author.ImageFile != null && author.ImageFile.ContentLength > 0)
                {
                    string uploadPath = Server.MapPath("~/Files/Images/");
                    authorImageService.UpdateAuthorImageData(ref author, uploadPath);
                }

                authorRepository.Update(author);
                authorRepository.Save();

                return RedirectToAction("Index");
            }

            return View(author);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Author author = authorRepository.GetById(id);

            if (author != null)
            {
                authorRepository.Delete(id);
                authorRepository.Save();

                return RedirectToAction("Index");
            }

            return HttpNotFound($"Author with id = {id} does not exist.");
        }

        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            Author author = authorRepository.GetById(id);

            if (author != null)
            {
                return View(author);
            }

            return HttpNotFound($"Author with id = {id} does not exist.");
        }
    }
}

Library.WebApplication/Views/Authors/Create.cshtml
@model Library.Entities.Author

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Authors", FormMethod.Post, new {enctype = "multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Author</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <input type="file" name="ImageFile" />
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Library.WebApplication/Views/Authors/Details.cshtml
@model Library.Entities.Author

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Author</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

    </dl>
</div>
<div>
    <img src="~/Files/Images/@Model.ImagePath" alt="Author image" height="200" width="200">
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Library.WebApplication/Views/Authors/Edit.cshtml
@model Library.Entities.Author

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Authors", FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <input type="file" name="ImageFile" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Library.WebApplication/Views/Authors/Index.cshtml
@model IEnumerable<Library.Entities.Author>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Surname)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id = item.Id })
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })

            }
        </td>
    </tr>
}

</table>