Library.WebApplication/Models/BookViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Library.Entities;

namespace Library.WebApplication.Models
{
    public class BookViewModel
    {
        [Required]
        public Book Book { get; set; }
        [Required]
        public int SelectedAuthorId { get; set; }
    }
}

Library.WebApplication/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Library.Entities;
using Library.Repositories.Implementation;
using Library.Repositories.Interfaces;
using Library.WebApplication.Models;
using Library.WebApplication.Services;

namespace Library.WebApplication.Controllers
{
    public class BooksController : Controller
    {
        private IRepository<Book> bookRepository;
        private IRepository<Author> authorRepository;
        private BookCoverService bookCoverService;

        public BooksController(IRepository<Book> repository, IRepository<Author> authorRepository)
        {
            bookRepository = repository;
            this.authorRepository = authorRepository;
            bookCoverService = new BookCoverService();
        }

        // GET: Books
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(bookRepository.GetAll());
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.Authors = PopulateAuthorsDropDownList();
            return View();
        }
        
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(BookViewModel model, HttpPostedFileBase ImageFile)
        {
            ViewBag.Authors = PopulateAuthorsDropDownList();

            if (ModelState.IsValid)
            {
                Book bookToCreate = model.Book;
                Author author = authorRepository.GetById(model.SelectedAuthorId);

                bookToCreate.AuthorId = author.Id;
                bookToCreate.Author = author;

                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    bookToCreate.ImageFile = ImageFile;
                    string uploadPath = Server.MapPath("~/Files/Covers/");
                    bookCoverService.UpdateBookCoverData(ref bookToCreate, uploadPath);
                }

                bookRepository.Create(bookToCreate);
                bookRepository.Save();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            ViewBag.Authors = PopulateAuthorsDropDownList();
            BookViewModel model = new BookViewModel();
            Book book = bookRepository.GetById(id);
            model.Book = book;
            model.SelectedAuthorId =  book.AuthorId.GetValueOrDefault(1);

            if (model.Book != null)
            {
                return View(model);
            }

            return HttpNotFound($"Book with specified id = {id} does not exist.");
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(BookViewModel model, HttpPostedFileBase ImageFile, int id)
        {
            ViewBag.Authors = PopulateAuthorsDropDownList();
            if (ModelState.IsValid)
            {
                Book bookToCreate = bookRepository.GetById(id);
                
                Author author = authorRepository.GetById(model.SelectedAuthorId);

                bookToCreate.AuthorId = author.Id;
                //bookToCreate.Author = author;
                

                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    bookToCreate.ImageFile = ImageFile;
                    string uploadPath = Server.MapPath("~/Files/Covers/");
                    bookCoverService.UpdateBookCoverData(ref bookToCreate, uploadPath);
                }

                //string uploadPath = Server.MapPath("~/Files/Covers/");
                //bookCoverService.UpdateBookCoverData(ref book, uploadPath);
                //bookRepository.Update(bookToCreate);
               // bookRepository.Save();
                bookRepository.Update(bookToCreate);
                bookRepository.Save();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Book book = bookRepository.GetById(id);

            if (book != null)
            {
                bookRepository.Delete(id);
                bookRepository.Save();

                return RedirectToAction("Index");
            }

            return HttpNotFound($"Book with specified id = {id} does not exist.");
        }

        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            Book book = bookRepository.GetById(id);

            if (book != null)
            {
                return View(book);
            }

            return HttpNotFound($"Book with specified id = {id} does not exist.");
        }

         private IEnumerable<SelectListItem> PopulateAuthorsDropDownList()
        {
            var authors = authorRepository.GetAll()
                .Select(n =>
                    new SelectListItem()
                    {
                        Value = n.Id.ToString(),
                        Text = $"{n.Name} {n.Surname}"
                    }).ToList();

            return new SelectList(authors, "Value", "Text");
        }
    }
}

Library.WebApplication/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Library.Entities;
using Library.Repositories.Interfaces;
using Microsoft.AspNet.Identity;

namespace Library.WebApplication.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly IRepository<Reservation> reservationsRepository;
        private readonly IRepository<Book> booksRepository;

        public ReservationsController(IRepository<Reservation> reservationsRepository,
            IRepository<Book> booksRepository)
        {
            this.reservationsRepository = reservationsRepository;
            this.booksRepository = booksRepository;
        }

        // GET: Reservations
        public ActionResult Index()
        {
            Reservation reservation = GetReservation();
            return View(reservation);
        }

        public ActionResult AddReservation(int bookId)
        {
            Reservation reservation = GetReservation();
            Book reservedBook = booksRepository.GetById(bookId);

            if (!reservation.ReservedBooks.Any(x => x.Id == bookId))
            {
                reservation.ReservedBooks.Add(reservedBook);
            }
            
            return RedirectToAction("Index");
        }

        public ActionResult RemoveBook(int id)
        {
            Reservation reservation = GetReservation();

            Book reservedBook = reservation.ReservedBooks.First(x => x.Id == id);

            if (reservedBook != null)
            {
                reservation.ReservedBooks.Remove(reservedBook);
            }

            return RedirectToAction("Index");
        }

        private Reservation GetReservation()
        {
            Reservation reservation = (Reservation) Session["Reservation"];
            if (reservation == null)
            {
                reservation = new Reservation();
                reservation.ReservedBooks = new List<Book>();
                var userName = HttpContext.User.Identity.GetUserName();
                reservation.UserName = userName;
                
                Session["Reservation"] = reservation;
            }

            return reservation;
        }

        public ActionResult Create()
        {
            Reservation reservation = GetReservation();
            return View(reservation);
        }

        [HttpPost]
        public void Create(Reservation reservation)
        {
            var reservedBooks = GetReservation().ReservedBooks;
            reservation.UserName = HttpContext.User.Identity.GetUserName();
            reservation.ReservedBooks = reservedBooks;
            reservationsRepository.Create(reservation);
            reservationsRepository.Save();
        }

        public ActionResult ListAll()
        {
            var reservations = reservationsRepository.GetAll().ToList();
            return View(reservations);
        }

        public ActionResult Delete(int id)
        {
            Reservation reservation = reservationsRepository.GetById(id);

            if (reservation != null)
            {
                reservationsRepository.Delete(id);
                reservationsRepository.Save();
                return RedirectToAction("ListAll");
            }

            return HttpNotFound("Reservation with specified id does not exist.");
        }
    }
}

Library.WebApplication/Views/Books/Create.cshtml
@model Library.WebApplication.Models.BookViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Books", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Book.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Book.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedAuthorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SelectedAuthorId", (SelectList)ViewBag.Authors, "Select author", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book.AuthorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Book.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Book.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <input type="file" name="ImageFile" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Library.WebApplication/Views/Books/Details.cshtml
@model Library.Entities.Book

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        
        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

    </dl>
</div>
<div>
    <img src="~/Files/Covers/@Model.ImagePath" alt = "Book cover" height="200" width="200">
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Library.WebApplication/Views/Books/Edit.cshtml
@model Library.WebApplication.Models.BookViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Books", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Book.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Book.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedAuthorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SelectedAuthorId", (SelectList)ViewBag.Authors, "Select author", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book.AuthorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Book.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Book.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <input type="file" name="ImageFile" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Library.WebApplication/Views/Books/Index.cshtml
@model IEnumerable<Library.Entities.Book>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new {id = item.Id})
            @Html.ActionLink("Add reservation", "AddReservation", "Reservations", new {bookId = item.Id}, null)
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Edit ", "Edit", new {id = item.Id}) 
                @Html.ActionLink("Delete", "Delete", new {id = item.Id})
            }
        </td>
    </tr>
}

</table>